import type { SettingDef } from './settings';

export const EXTRA_SETTINGS: SettingDef[] = [
  {
    id: 'fete',
    names: ['the Little Wobbling Village Fete', 'the Upper Snoring Summer Show', 'the Much Pudding Flower Fair'],
    era: 'Modern English village summer fete',
    noun: 'the fete',
    blurb: {
      comedic: "{setting} was going swimmingly: the tombola was rigged, the cake was dry and the chairperson was, unexpectedly, dead. The tea tent remains open.",
      serious: "At {setting}, the well-loved chairperson is found dead beside the tea urn. Half the village was there, and every one of them had a reason to smile.",
      noir: "The bunting hung limp over {setting}. In a village this small, everyone knows everyone's business, and someone had just made it very personal.",
    },
    victim: { label: 'the fete chairperson', bio: "{name} has chaired the fete for thirty years and rules the raffle, the tea tent and the parish with an iron trowel." },
    rooms: ['the tea tent', 'the produce marquee', 'the bric-a-brac stall', 'the cricket pavilion', 'the church hall', 'the tombola stall', 'the vicarage garden', 'the beer tent'],
    methods: [
      { cause: 'poisoned by a slice of rhubarb cake', place: 'the tea tent', weaponTitle: 'Half-eaten cake slice', weaponDesc: 'A half-eaten slice of rhubarb cake abandoned on a paper plate, its custard smelling faintly of bitter almonds.', knew: 'that it was the cake, not the tea, that had done it' },
      { cause: 'struck by a prize marrow', place: 'the produce marquee', weaponTitle: 'Dented prize marrow', weaponDesc: 'The champion marrow, dented and streaked with something dark, hidden under the trestle-table cloth.', knew: 'that the marrow was the weapon, before anyone had lifted the tablecloth' },
    ],
    props: ['Bunting', 'A raffle drum and tickets', 'Paper plates and a tea urn', 'A rosette for the winner', 'A gong or bell for the announcements'],
    dress: ['Floral dresses and sun hats', 'Tweed jackets and wellies', 'Vicar in a dog collar', 'Stallholders in aprons'],
    accents: ['Warm West Country burr', 'Fussy home-counties', 'Gruff Yorkshire', 'Breathless village gossip', 'Posh committee chair'],
    startHour: 13,
    roles: [
      { label: 'the village vicar', honorific: 'Reverend', secret: 'The Vicar Who Bets on the Horses', bio: "{c} has seen the village through baptisms, weddings and quite a lot of jam, and is unfailingly kind to everyone in earshot.", back: "You have been borrowing from the church roof fund to cover a run of unlucky horses. {v} audited the roof fund last week.", costume: "Black clerical shirt, dog collar, a thermos of tea" },
      { label: 'the prize-winning jam maker', secret: 'The Jam Stealer', bio: "{c} has won the jam category eleven years running and will say so, with a smile, to anybody who slows down.", back: "Your prize preserve is your late neighbour's recipe, which you found in a drawer. {v} suspects.", costume: "Gingham apron, a jar in each hand, a rosette on the lapel" },
      { label: 'the parish council clerk', secret: 'The Keeper of the Minutes', bio: "{c} writes down everything that is said in the village, and reads it back at inconvenient moments.", back: "You quietly altered the minutes of a planning meeting to favour a friend. {v} had the originals.", costume: "Cardigan, lanyard and an enormous clipboard" },
      { label: 'the pub landlord', secret: 'The Publican Who Waters the Ale', bio: "{c} runs the beer tent, keeps every rumour and knows exactly how much you owe.", back: "You are behind on the brewery bill and have been quietly cutting the ale with water. {v} likes to sample the tent's wares.", costume: "Waistcoat, rolled sleeves and a tea towel over one shoulder" },
      { label: 'the champion gardener', secret: 'The Grower Who Cheats', bio: "{c} has grown giant vegetables to national acclaim, and treats every rival like a personal insult.", back: "Your prize marrows are grown with something not in the rulebook. {v} was about to check the ingredients.", costume: "Wellies, a battered straw hat and a fleece with a trowel tucked in the pocket" },
      { label: 'the antiques dealer', secret: 'The Dealer Who Sells Fakes', bio: "{c} runs the bric-a-brac stall and can tell a genuine Ming vase from a fake at ten paces, or claims to.", back: "Half your stock is reproduction, sold at a premium. {v} bought one and had it valued.", costume: "Waxed jacket, half-moon glasses and a magnifying loupe" },
    ],
  },
  {
    id: 'gallery',
    names: ['the Meridian Gallery', 'the Halcyon Museum of Modern Art', 'the Blackwell Gallery'],
    era: 'Modern art-gallery gala opening night',
    noun: 'the gallery',
    blurb: {
      comedic: "{setting} was about to unveil its most important exhibition, an unmade bed, a pile of bricks and, as of tonight, a body. The critics call it very bold.",
      serious: "At the gala opening of {setting}, its owner is found dead among the exhibits. The guests are collectors, critics and artists, and every one has an angle.",
      noir: "The chandeliers of {setting} threw cold light on warm money. The owner was dead by the sculptures, and nobody liked to say what price the art had really cost.",
    },
    victim: { label: 'the gallery owner', bio: "{name} owns {setting}, discovers genius, sells it at a premium and, it is whispered, occasionally manufactures it." },
    rooms: ['the main hall', 'the sculpture court', 'the restoration studio', 'the vault', 'the cloakroom', 'the rooftop terrace', 'the gift shop', "the curator's office"],
    methods: [
      { cause: 'struck with a bronze sculpture', place: 'the sculpture court', weaponTitle: 'The bronze figure', weaponDesc: 'A small bronze figure, wiped with a linen napkin and put back on its plinth slightly crooked, one edge still tacky.', knew: 'that the sculpture had been moved and wiped, before anyone had noticed it' },
      { cause: 'poisoned in a glass of gala champagne', place: 'the main hall', weaponTitle: 'The lipstick-smudged flute', weaponDesc: 'A single champagne flute smudged with lipstick and slipped under a plinth, its dregs smelling faintly of bitter almonds.', knew: 'that the poison was in the champagne, not the canapes' },
    ],
    props: ['Wine glasses and a tray of canapes', 'Small easel cards with fictional artwork titles', 'A velvet rope', 'A guest book and pen', 'A spotlight or desk lamp'],
    dress: ['Black cocktail dress and statement jewellery', 'Artist in paint-splattered overalls', 'Critic in dark glasses and a cape', 'Security in a blazer with an earpiece'],
    accents: ['Pretentious art-world drawl', 'Clipped Parisian', 'Gruff New York', 'Nervous student', 'Silky Italian dealer'],
    startHour: 19,
    roles: [
      { label: 'the star artist', secret: 'The Genius Who Cannot Paint', bio: "{c} is the toast of the season, an original talent who tells everyone that their work explains itself.", back: "Your breakthrough canvases were painted by a former student. {v} holds the receipts.", costume: "Paint-splattered black clothes and wild hair" },
      { label: 'the art critic', secret: 'The Critic Who Was Paid', bio: "{c} can make a career with a single adjective and end one with a raised eyebrow.", back: "You wrote glowing reviews for money, and {v} kept the payment ledger.", costume: "Dark cape, round glasses and a leather notebook" },
      { label: 'the curator', secret: 'The Keeper of the Vault', bio: "{c} knows every painting by heart and, it is said, every dust-mote on it, and is intensely protective of both.", back: "You quietly sold a minor work from the collection to cover a debt. {v} was about to audit the inventory.", costume: "Immaculate white gloves and a lanyard of keys" },
      { label: 'the restorer', secret: 'The Master of the Fake', bio: "{c} can bring a ruined canvas back to life with a steady hand and a very sharp knife.", back: "You painted a forged masterpiece for {v} years ago, and you have been paid in silence ever since.", costume: "Painter's smock with a magnifier on a cord" },
      { label: 'the wealthy collector', secret: 'The Buyer With Empty Walls', bio: "{c} buys anything with a famous signature and lets it gather dust in a warehouse.", back: "You paid a fortune for a painting {v} swore was real. You have just learned it is not.", costume: "Bespoke suit, a jewelled cufflink and a very large cheque book" },
      { label: 'the security guard', secret: 'The Guard Who Sleeps', bio: "{c} stands very still by the exit and sees everything, or so the rumours say.", back: "You have been sneaking out for a smoke and leaving the vault door on the latch. {v} saw the camera log.", costume: "Dark uniform, radio earpiece and a torch" },
    ],
  },
  {
    id: 'station',
    names: ['Polaris Station', 'the Halvorsen Research Base', 'the Aurora Ice Station'],
    era: 'Modern polar research station in midwinter',
    noun: 'the station',
    blurb: {
      comedic: "{setting} is six months into the polar night, with cabin fever, a very small chocolate ration and a dead station director. The penguins refuse to comment.",
      serious: "Cut off by a storm, {setting} is a hundred miles from anywhere. The director is dead and there are only nine people on the ice.",
      noir: "Nothing moved on the ice around {setting} but the wind and whatever was left of the truth. The director was dead, and the winter was long.",
    },
    victim: { label: 'the station director', bio: "{name} runs {setting} with a clipboard and a whistle, and holds the only satellite phone, the grant money and the last word." },
    rooms: ['the mess hall', 'the laboratory', 'the generator shed', 'the radio room', 'the greenhouse dome', 'the bunk room', 'the airlock', 'the observatory'],
    methods: [
      { cause: 'locked outside in the deep cold', place: 'the airlock', weaponTitle: 'The jammed latch', weaponDesc: 'The outer airlock latch was jammed from the inside with a length of cable, and the safety override wired dead.', knew: 'that the airlock had been jammed from the inside, when the log said it had merely frozen shut' },
      { cause: 'poisoned in a tampered mug of coffee', place: 'the mess hall', weaponTitle: 'The untouched mug', weaponDesc: 'A single mug of cold coffee, set apart on the mess-hall table, its surface skinned with something oily.', knew: 'that it was the coffee, not the stew, that was tampered with' },
    ],
    props: ['Thermos flasks', 'A wall map of the ice', 'Radio or walkie-talkies', 'Ski goggles and hats', 'Wool blankets'],
    dress: ['Heavy parkas and woollen hats', 'Lab coats over thermals', 'Bright orange expedition jackets', 'Ice-crusted boots (optional)'],
    accents: ['Crisp Norwegian', 'Laconic Australian', 'Sardonic New England', 'Gentle Scottish', 'Fast-talking postdoc'],
    startHour: 18,
    roles: [
      { label: 'the climatologist', secret: 'The Scientist With Fudged Data', bio: "{c} measures the ice to the millimetre and has strong opinions about everyone else's measurements.", back: "You smoothed the data in your latest paper to secure the next grant. {v} had the raw files.", costume: "Thermal layers, a clipboard and a frosted notebook", },
      { label: 'the station medic', honorific: 'Dr.', secret: 'The Doctor Without a Licence', bio: "{c} treats every ailment from frostbite to homesickness with the same calm bedside manner.", back: "Your medical licence lapsed years ago. {v} discovered the paperwork mid-winter.", costume: "Red medical bag over a heavy parka" },
      { label: 'the radio operator', secret: 'The Voice on the Line', bio: "{c} talks to the outside world every day and passes the news along, when they feel like it.", back: "You have been deleting messages from the log for a friend. {v} noticed the gaps.", costume: "Headphones round the neck and a scarf up to the ears" },
      { label: 'the mechanic', secret: 'The Person Who Sabotages', bio: "{c} keeps the generators running through the cold and will fix anything, given time and a big enough wrench.", back: "You have been siphoning fuel to sell on the next supply run. {v} started to check the tanks.", costume: "Grease-streaked overalls and a woollen hat" },
      { label: 'the station cook', secret: 'The Cook Who Rations Cruelly', bio: "{c} makes miracles from tinned beans and tells everyone that the dessert is a surprise.", back: "You have been hoarding the good food in a private stash. {v} did a stock count last week.", costume: "Stained apron, oven mitts and a wooden spoon" },
      { label: 'the doctoral student', secret: 'The Keen Recruit', bio: "{c} is here for the science, the adventure and the extra credit, and is a little too enthusiastic about all three.", back: "You wrote a data script that quietly erased another researcher's results. {v} asked to see the code.", costume: "A brand-new parka with the tags still on" },
    ],
  },
  {
    id: 'riverboat',
    names: ['the Delta Duchess', 'the Magnolia Queen', 'the Copper Belle'],
    era: '1880s Mississippi paddle-steamer casino',
    noun: 'the steamer',
    blurb: {
      comedic: "{setting} was the finest casino on the river until the owner turned up dead. The card sharps offer condolences and a slightly better deal.",
      serious: "Adrift in a midnight fog, {setting} carries a killer among its passengers. The next landing is hours away.",
      noir: "The paddle wheel churned the muddy water of the river and washed away the evidence. The owner never made it to the next landing.",
    },
    victim: { label: 'the boat owner', bio: "{name} owns {setting} and the fortunes of nearly everyone who plays on it, and is never seen without a pistol and a smile." },
    rooms: ['the gaming saloon', 'the promenade deck', 'the paddle house', "the captain's cabin", 'the galley', 'the boiler deck', "the ladies' lounge", 'the cargo hold'],
    methods: [
      { cause: 'shot with a derringer', place: 'the gaming saloon', weaponTitle: 'The little derringer', weaponDesc: 'A tiny pearl-handled derringer, dropped behind a card table with one chamber spent and the barrel still warm.', knew: 'that the shot came from a derringer, not the revolver everybody assumed' },
      { cause: 'poisoned in a glass of bourbon', place: 'the promenade deck', weaponTitle: 'The abandoned glass', weaponDesc: 'A glass of bourbon left on the rail, half drunk, with a bitter, medicinal smell rising from it.', knew: 'that the bourbon, not the punch, had been spiked' },
    ],
    props: ['Playing cards and chips', 'A brass bell', 'A ship\'s wheel or lifebelt', 'Oil lamps or battery lanterns', 'Sarsaparilla and whiskey glasses'],
    dress: ['Gambler in a brocade waistcoat', 'Southern belle in a hooped skirt', 'Steamboat captain in a peaked cap', 'Deckhand in braces and a neckerchief'],
    accents: ['Slow Louisiana drawl', 'Sharp New Orleans patter', 'Preacher\'s thunder', 'Gruff Missouri boatman', 'Silky card-sharp'],
    startHour: 21,
    roles: [
      { label: 'the card sharp', secret: 'The Gambler Who Always Wins', bio: "{c} has never left a table poorer and has never been caught cheating, which is a very different thing.", back: "You were cheating at the owner's table. {v} was about to have the deck examined.", costume: "Brocade waistcoat, silk cravat and a hidden ace" },
      { label: 'the riverboat pilot', secret: 'The Pilot Who Lost the Channel', bio: "{c} reads the river like a book and steers by smell, or so the crew swear.", back: "You ran the boat aground last spring and hid the damage report. {v} found the carbon copy.", costume: "Peaked cap and a well-worn captain's coat" },
      { label: 'the travelling preacher', honorific: 'Reverend', secret: 'The Preacher Who Is No Such Thing', bio: "{c} preaches every night on the promenade deck and takes a collection for the poor.", back: "You have never been ordained and the collection funds a very comfortable lifestyle. {v} asked to see your papers.", costume: "Black frock coat, white collar and a battered Bible" },
      { label: 'the saloon singer', secret: 'The Star With a Past', bio: "{c} sings the sweetest songs on the river and shuts the room up with a look.", back: "You run from a marriage you never mention, and {v} had a detective looking for you.", costume: "Feathered gown, long gloves and a sparkling comb" },
      { label: 'the cotton broker', secret: 'The Broker With Two Ledgers', bio: "{c} trades in bales and bills and treats every friendly chat as a negotiation.", back: "You inflated the weight of your cargo to swindle the buyers, and {v} weighed a bale personally.", costume: "Linen suit, boater hat and a heavy money belt" },
      { label: 'the steamboat engineer', secret: 'The Engineer Who Tampers', bio: "{c} keeps the boilers roaring and is covered in soot, oil and quiet pride.", back: "You skimped on boiler maintenance to pocket the money. {v} was about to inspect the gauges.", costume: "Soot-streaked overalls and a red bandana" },
    ],
  },
];
